name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore

    - name: Build Solution
      run: |
        msbuild.exe ACT_Chat.sln /p:platform="Any CPU" /p:configuration="Release" 

    - name: Run ACT_ChatTests
      run: vstest.console.exe ACT_ChatTests\bin\Release\ACT_ChatTests.dll

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ACT Plugin
        path: ACT_Chat\bin\Release\ACT_Chat.dll
        if-no-files-found: error
